export const GET_POTHOLE_DATA_REQUEST='GET_POTHOLE_DATA_REQUEST' ;
export const GET_POTHOLE_DATA_SUCCESS='GET_POTHOLE_DATA_SUCCESS' ;
export const GET_POTHOLE_DATA_FAIL='GET_POTHOLE_DATA_FAIL' ;



export const UPDATE_POTHOLE_REQUEST='UPDATE_POTHOLE_REQUEST' ;
export const UPDATE_POTHOLE_SUCCESS='UPDATE_POTHOLE_SUCCESS' ;
export const UPDATE_POTHOLE_FAIL='UPDATE_POTHOLE_FAIL' ;

export const SEND_IMAGE_REQUEST='SEND_IMAGE_REQUEST' ;
export const SEND_IMAGE_SUCCESS='SEND_IMAGE_SUCCESS' ;
export const SEND_IMAGE_FAIL='SEND_IMAGE_FAIL' ;